version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: adv-yolo-frontend
    ports:
      - "3000:3000" 
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: adv-yolo-backend
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
